### ISSUE TITLE
Can someone writeup a navigation bar for scalica?

### ISSUE THREAD

**Issue by Matthew-Nwen** [BlindGhosty/LSWA-Project#1]

**Comment by kpwill** [comment]
sure, what do we want in it? home (the feed), my feed (logged in user's posts), followers, followees? anything else?

**Comment by Matthew-Nwen** [comment]
Home and Recommendation seem the only bit needed for workflow atm.

**Comment by kpwill** [comment]
Done. Just pushed it.  Clicking user name links to home and i added the recommendations link, lemme know if there are any issues

**Comment by Matthew-Nwen** [comment]
Awesome.
